name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build: 

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: make

